### ISSUE TITLE
Ase.DataReader.Read() throwing "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by FrankWendel** [DataAction/AdoNetCore.AseClient#102]
I'm trying to call a procedure, that have several parameters and i'm using Linq2db, but after call "Read" method i'm getting an exeception called "IndexOutOfRangeException", see the stacktrace below:

 `System.IndexOutOfRangeException: Index was outside the bounds of the array.\r\n   at AdoNetCore.AseClient.AseDataReader.Read()\r\n   at LinqToDB.Data.CommandInfo.ReadEnumerator[T](IDataReader rd, Func'2 objectReader)+MoveNext()\r\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable'1 source, Boolean& found)\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable'1 source)\r\n[...]`

Anyone know what can i be doing to cause this? #

**Comment by senseibaka** [comment]
Possibly it's an interaction between `Linq2Db`'s code and `AseDataReader`.

I'd say that `AseDataReader` probably needs to handle unexpected calls to `Read()`, etc., better.

Can you supply a cut-down version of your stored procedure which reproduces this problem?

Cheers

**Comment by FrankWendel** [comment]
First, thanks for the answer!

```
create procedure cut_down_proc

@NUM_PDV            numeric(9),
@NUM_FCT            int,
@COD_TIP_ACAO_FCT   tinyint,
@COD_INDC_REG_ATU   char(1),
@COD_SIT_FCT        char(1),
@COD_TERM_DST       char(8),
@COD_TIP_EQPM       char(3),
@IND_TCNL_CMPH      char(1),
@COD_CNL_DSTR       numeric(2),
@COD_CEL_DSTR       int,
@DTH_ASSN_CTR_POS   datetime,
@VAL_INI_ALGL       numeric(9, 2),
@COD_INDC_ISN_ALGL  char(1),
@DTH_FIM_ISN_ALGL   datetime,
@COD_INDC_ECLM      char(1),
@COD_EVN_ESPC       char(2),
@COD_TIP_LGCO       tinyint,
@COD_VDA_DGTD_POS   char(1),
@COD_INDC_PRRD      char(1),
@DTH_LIM_PRRD       datetime,
@COD_DFR_END        char(1),
@NOM_END_TERM       char(60),
@NUM_END_TERM       char(6),
@NOM_END_CPL_TERM   char(100),
@NOM_BRR_TERM       char(20),
@NOM_CID_TERM       char(50),
@NOM_EST_TERM       char(2),
@COD_CEP_TERM       char(5),
@COD_CEP_CPL_TERM   numeric(3),
@NUM_DDD_TERM       char(4),
@NUM_TEL_TERM       int,
@NOM_PES_CTTO       char(50),
@COD_TERM           char(8),
@NUM_HDSK_ESTB      int,
@COD_HRRO_SMNA_INI  numeric(1),
@COD_HRRO_SMNA_FIM  numeric(1),
@HOR_INI_FNCN       numeric(4),
@HOR_FIM_FNCN       numeric(4),
@DES_OBS_FCT        varchar(255),
@COD_FBRC_HDW       char(2),
@COD_FORN_SFTW      char(2),
@COD_INTG           char(2),
@COD_TIP_CNXO       int,
@COD_VERS_SFTW      int,
@NUM_RNPC           numeric(15),
@COD_PRPT_TERM      tinyint,
@QTD_CHCK_OUT       int,
@COD_INDC_TEM_PNPD  char(1),
@COD_OPID_ULT_ATLZ  char(8),
@NUM_ULT_SEQ_FCT    int,
@NUM_ANT            int,
@COD_TIP_NMRC       tinyint,
@TIMESTAMP          varchar(255),
@NUM_FCT_ORI        int,
@NUM_PDV_ORI        numeric(9),
@TIMESTAMP_ORI      varchar(255),
@COD_INDC_VLDC_ENDR char(1),
@COD_ACAO_CMC       tinyint,
@COD_PRRD_NEGC      tinyint,
@IND_ISN_PGMN       char(1),
@COD_CNRO           int,
@IND_SZND           char(1),
@NUM_FLCO_AMEX      numeric(16),
@NUM_FLCO_VISA      numeric(16),
@NUM_FCT_ANT        int         = null ,    -- desv12795
@COD_ORG_SLC_FCT    tinyint     = 0,
@IndTermFatrExps    char(1)     = 'N'

AS

   select 0 as cod_err, 'sucesso' as des_err , 0
```

Another thing that i did not mentioned before, was that this error only happens on stage environment, it works on my machine (lol), sybase version could be the reason of the error?

**Comment by c-j-hughes** [comment]
Hey @FrankWendel,

I've created a test with the proc code above, and can't reproduce. 

You can [view the branch here](https://github.com/DataAction/AdoNetCore.AseClient/tree/data-reader-read-throws). Perhaps you could run the test on the system that fails?

I suspect this may be an environment thing. We only test on ASE 15.x and 16x, so if it was a 12.x your mileage would vary.
