### ISSUE TITLE
DbProviderFactories configuration

### ISSUE THREAD

**Issue by flyeagle7268** [DataAction/AdoNetCore.AseClient#103]
Does AseClient support DbProivderFactories? How can I configure in appsettings.json file

 <system.data>
    <DbProviderFactories>
      <add name="Microsoft SQL Server Compact Data Provider" invariant="System.Data.SqlServerCe.3.5" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"/>
    
    </DbProviderFactories>
  </system.data>

**Comment by senseibaka** [comment]
Hi @flyeagle7268 

Yes, I think we support `DbProviderFactories`, when running in .net core 2.1/2.2 or .net framework - see https://github.com/DataAction/AdoNetCore.AseClient/blob/master/src/AdoNetCore.AseClient/AseClientFactory.cs

However, I do not know how to configure `DbProviderFactories` in appsettings.json. The MSDN documentation might be more helpful in that matter...

Failing that, you might have to call the `RegisterFactory` method https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbproviderfactories.registerfactory?view=netcore-2.2#System_Data_Common_DbProviderFactories_RegisterFactory_System_String_System_Data_Common_DbProviderFactory_
