### ISSUE TITLE
Support NamedParameters = false

### ISSUE THREAD

**Issue by sheikhjabootie** [DataAction/AdoNetCore.AseClient#13]
SAPs AseClient allows AseCommands to be executed like the following:

- `SELECT * FROM myTable WHERE myColumn = ?`
- `SELECT * FROM myTable WHERE myColumn = @myColumn`

We support the latter syntax, but not the former. 

To place the AseCommand in the former mode, either it or the owning AseConnection can have their NamedParameters property set to false.

We should add this support.

**Comment by senseibaka** [comment]
The .net 4 driver parses the input sql and replaces ? entries with named parameters following the scheme `@dr_ta[index]`

Appears to be support for the return value in `exec ?=stored_procedure_name`
