### ISSUE TITLE
Nuget build/pack deprecated some elements

### ISSUE THREAD

**Issue by senseibaka** [DataAction/AdoNetCore.AseClient#146]
> warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
> warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl

**Comment by c-j-hughes** [comment]
Fixed
