### ISSUE TITLE
I don't get rows when I ask about Sybase Anywhere 10

### ISSUE THREAD

**Issue by MarianoGomezBidondo** [DataAction/AdoNetCore.AseClient#151]
Hi!
Im using Dot Net core 2.2 with SQL Anywhere Network Server Version 10.0.1.4310, windows (of course).

When making a select of a table of only 12 records and two fields, I don't get values.

The connection is made without error and the state that the connection object returns "Open". When making a select the reader gives no error, but when making a reader.read() there are simply no records.

I did the same example with .Net Framework 4.8 and Adoconnection and it works.

IIs it supposed to work on that old version of Sybase?

Regards!

**Comment by c-j-hughes** [comment]
Hey @MarianoGomezBidondo,

I'm afraid we only support Adaptive Server Enterprise (ASE) on v15.x+, as this is the only platform we have test environments for. If the driver works at all with SQL Anywhere, it is by accident.

We do get quite a few issues about SQL Anywhere support, so could be a future direction for the project, but we'd need broader community support, or even SAP support to get there.
