### ISSUE TITLE
AseDataReader.RecordsAffected doesnt return correct value

### ISSUE THREAD

**Issue by sgwyn** [DataAction/AdoNetCore.AseClient#153]
I've noticed the RecordsAffected property doesn't seem to behave as expected. Does anybody else experience the same problem?

AseDataReader.RecordsAffected returns 0 for all Update, delete and insert statements, returns row count for select statements

according to other implementations of DataReader including Sybase documentation it should return The number of rows changed, inserted, or deleted; 0 if no rows were affected or the statement failed; and -1 for SELECT statements.

**Environment**
- Core 2.2
- AdoNetCore.AseClient 0.16

**Comment by senseibaka** [comment]
Hi @sgwyn good find. It appears our implementation of `RecordsAffected` is incorrect.

I'll add a fix to the next release

**Comment by c-j-hughes** [comment]
@sgwyn - heard you had a fix for this. Can you send a PR?
