### ISSUE TITLE
Arithmetic overflow during implicit conversion of NUMERIC value '2819.0444' to a NUMERIC field .

### ISSUE THREAD

**Issue by bbarry** [DataAction/AdoNetCore.AseClient#173]
When using decimal output parameters and calling a stored procedure, we are getting various scale and precision errors depending on the value of the stored procedure.

Example procedure:

    CREATE PROCEDURE dbo.Test184(@TotalValue numeric(18,4) = 0 output)
    AS    
    set @TotalValue = 2819.0444

C# to reproduce issue:

    using var connection = AseClientFactory.Instance.CreateConnection();
    connection.ConnectionString = Constants.ConnectionString;
    connection.Open();
    var cmd = connection.CreateCommand();
    cmd.CommandText = "Test184";
    cmd.CommandType = CommandType.StoredProcedure;
    var total = new AseParameter()
    {
        ParameterName = "@TotalValue",
        AseDbType = AseDbType.Decimal,
        Direction = ParameterDirection.Output,
        Precision = 18,
        Scale = 4,
    };
    cmd.Parameters.Add(total);

    cmd.ExecuteNonQuery();

Expected: no errors

Actual: `AdoNetCore.AseClient.AseException : Arithmetic overflow during implicit conversion of NUMERIC value '2819.0444' to a NUMERIC field .`

.Net Core 3.1 or .Net Framework 4.8

AdoNetCore.AseClient 0.16.0

SAP ASE 16 PL07, also happens against PL03 (these are the versions of ASE I have connections to); similar code on .net framework works with Sybase.AdoNet4.AseClient.dll (testing with 16.0.3.0)

**Comment by ryan-payet-wcc** [comment]
I had a similar issue with an output parameter.  I got it working using DbType = DbType.Int64
exaample `	new AseParameter("@batch_posfix", AseDbType.Numeric, 10) {  Direction = ParameterDirection.Output, Scale = 10, Precision = 0, DbType = DbType.Int64 }`

**Comment by bbarry** [comment]
In our case we have this working with the currency type but it seems like there is a problem with output parameters that have variable sizes?
