### ISSUE TITLE
Any plans to add Entity Framework Core support?

### ISSUE THREAD

**Issue by Dennis-Petrov** [DataAction/AdoNetCore.AseClient#181]
Greetings!
Are there any plans to add Entity Framework Core support?

**Comment by formicas** [comment]
Hey @Dennis-Petrov,
Short answer - no.

We're focusing our development on our own needs, and this isn't one of them. That doesn't mean we're not happy to entertain PRs for other features. It depends on the level of complexity too. We'd want to avoid introducing significant maintenance overhead.

**Comment by thancock14** [comment]
https://github.com/spasarto/EntityFrameworkCore.Ase

have you tried this?

**Comment by Dennis-Petrov** [comment]
@formicas , thanks for clear answer.
@thancock14 , no, but I'll take a look on it, thanks.

As a side note: every thing SAP touches turns into sh..t. Some sort of anti-Midas.
Closing this.

**Comment by MaceWindu** [comment]
@formicas , maybe it makes sense to add orm support section to readme with https://github.com/spasarto/EntityFrameworkCore.Ase and https://github.com/linq2db/linq2db listed?

@Dennis-Petrov ,
If you need orm support you can try https://github.com/linq2db/linq2db directly or using our ef.core bridge https://github.com/linq2db/linq2db.EntityFrameworkCore
