### ISSUE TITLE
ExecuteReader() intermittently throws System.Data.ConstraintException

### ISSUE THREAD

**Issue by ngvtien** [DataAction/AdoNetCore.AseClient#183]
**Describe the bug**
**ExecuteReader()** intermittently throws **System.Data.ConstraintException** with error message: _Failed to enable constraints. One or more rows contain values violating non-null, unique, or foreign-key constraints._

Note: this behavior only happen when **EnforceConstraints** property of the DataSet is set to **true** which is the default setting by the DataSet class.

The library relies on the **sp_oledb_getindexinfo** stored proc to determine the table columns metadata definition for **Unique** and **PrimaryKey** where one would have thought that there should be only one row per column name but I've came across a situation where there are more one row of different metadata return for a given column name and when this happen, the **SchemaTableBuilder** class becomes unstable when **TryLoadKeyInfo** method is called and as a result the above exception is thrown.

Below is the output from the **sp_oledb_getindexinfo** stored proc mention above. Notice duplicate column name with different metadata.
![image](https://user-images.githubusercontent.com/11168491/86006852-c054f080-ba55-11ea-8399-b9c49d6110b2.png)

**Expected behavior**
It should work similar to the legacy driver

**Environment**
- .NET Framework 4.6.2
- `AdoNetCore.AseClient` nuget package version 0.18.0

**Additional context**
As a workaround I only use one metadata row per column name but even that is not a fix because the data might contradict the column metadata and you would still get the above exception thrown.

I think we should find any alternative for **sp_oledb_getindexinfo** where column's metadata uniqueness is guarantee.

**Comment by bbarry** [comment]
Do you have a script that reproduces this? We are using readers quite heavily and haven't had any issues

**Comment by ngvtien** [comment]
Same here and I was surprise to catch this one out too as more than 90% of my other test cases pass.

If you run the sql script below against your database, it's more than likely that you get back a unique rows but it's not always guarantee.

_exec database_name..sp_oledb_getindexinfo @table_name = 'some_table_name', @table_owner='dbo', @table_qualifier='database_name'_

I've tried with the legacy driver and it works fine on the same data.

The usual standard c# code is as shown below

var paramVal1 = 2343;
var paramVal2 = 4390;
using (var connection = ......)
{
    using (var command = connection.CreateCommand(connection.Transaction, "some_stored_proc"))
    {
        command.SetParameter("@someParameter", paramVal1, DbType.VarNumeric, ParameterDirection.Input);
        command.SetParameter("@someOtherParameter", paramVal2, DbType.VarNumeric, ParameterDirection.Input);

        try
        {
            var results = new DataSet();
            using (var reader = command.ExecuteReader())
            {
                results.Load(reader, LoadOption.OverwriteChanges, tableNames);
            }
            return results;

        }
        catch (Exception ex)
        {
            throw;
        }
    }
}

**Comment by ngvtien** [comment]
Spent quite some times looking for the alternative way to obtain the **IsUnique** and **IsKey** column metadata value without any success, it seems that the server doesn't sending back those values reliably and accurately. So we still have to rely on the stored proc but if we found any duplicate with column name then we won't set those 2 metadata value. I have put in a PR for this issue and the previous one [182](https://github.com/DataAction/AdoNetCore.AseClient/issues/182)

**Comment by formicas** [comment]
@ngvtien What's your solution? The reference driver somehow handles this - does it use the proc?

**Comment by ngvtien** [comment]
we have a dictionary to keep track of any duplicate column name
