### ISSUE TITLE
Getting timeout when trying to connect

### ISSUE THREAD

**Issue by cwoolum** [DataAction/AdoNetCore.AseClient#20]
When I try to open a new connection, I get the following error:

```
AseException: Timed out trying to establish a connection
AdoNetCore.AseClient.Internal.ConnectionPool.Reserve()
```

Could I be doing something wrong? My code looks like:

```
using (var test = new AseConnection("Data Source=sybase;Port=5000;Database=gravity;Uid=sa;Pwd=myPassword;pooling=false;"))
{
    test.Open(); // Blows up here
    test.ExecuteScalar<int>("Select (1)");
 }
```

I know my server is running because I can connect to it with DBeaver.

**Comment by senseibaka** [comment]
Hi @cwoolum, currently we don't support reading from the sybase.ini file, so if your data source is defined there it won't work. This is something we should think about implementing...

In the meantime, can you try specifying the server's IP address or DNS name instead and see what happens?

Thanks

**Comment by senseibaka** [comment]
Sorry, by sybase.ini I meant sql.ini

**Comment by cwoolum** [comment]
I'm not using sql.ini to connect. Sybase is the hostname of the docker container that hosts my sybase instance. Let me try by IP and see if that works. DNS usually resolves correctly but there could be something weird happening.

**Comment by senseibaka** [comment]
Ah, interesting, it might be useful for us to set up a test case of some sort. Let us know how it goes

**Comment by cwoolum** [comment]
Okay, I tested with IP address but I'm still getting the same error. I'm running this on an empty Linux instance with nothing else installed. Are there any other dependencies that are required?

**Comment by senseibaka** [comment]
Beyond having .net core 1 or 1.1 or 2 installed, there should be no dependencies

**Comment by cwoolum** [comment]
I'm starting to think this might be a Linux related issue. I ran the app in Windows and was able to connect to by db fine. When I ran it from inside the Linux container, I had the error again. 

Because of a VPN issue, I can't test against an external Sybase db right now while running inside of Linux. I'll try to replicate the issue another way.

**Comment by cwoolum** [comment]
This was a configuration error on my part. Sorry!

**Comment by senseibaka** [comment]
No worries, glad you figured it out :)
