### ISSUE TITLE
Does anyone have this working in a .net core 3.1?

### ISSUE THREAD

**Issue by CrazyLichApps** [DataAction/AdoNetCore.AseClient#204]
I was just checking to see if anyone has been able to use this in a core 3.1 project.

I can get a connection to open but can not get anything back from my query, it seems to be timing out and I do not get an error.

I have tried using ExecuteReader and DataAdapter and get the same result.

I didn't post any code or anything until I know for sure that it actually works with 3.1.

Thanks

**Comment by MaceWindu** [comment]
We successfully use it to test [linq2db](https://github.com/linq2db/linq2db) with Sybase ASE 16.0 using .net core under linux and macos.

Note that we use 0.18.0 version due to #203 (not tested 0.19.2 with fix yet)

**Comment by bbarry** [comment]
I was using this in production in a 3.1 project. The project has been upgraded to 5.0 though (using the same library and version).

**Comment by CrazyLichApps** [comment]
Thank you so much, I must just be doing something wrong. Maybe I will try uninstalling and reinstalling the 0.18.0 version and give that a try first. Thanks again for your quick replies.

**Comment by MaceWindu** [comment]
That's interesting. After update to 0.19.2 from 0.18.0 we now getting stable `AseException : There is no server listening at localhost:5000.` in our azure CI (but it works for me locally). Will check it later and report new issue if I will find what's wrong.
