### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by SouzaRodrigo61** [DataAction/AdoNetCore.AseClient#229]
**Is this library still supported?**

I ask this because the last commit is from 2021.

**Comment by Ju42** [comment]
Hello, I think you can consider this repo as unmaintained until further notice as the maintainer did not have the time to handle incoming PR nor to reply to issue since 2021. I've been monitoring it since 2021 to see if the pending PR could get merged at some point but for now they aren't.
