### ISSUE TITLE
Planned support for .net Standard 2?

### ISSUE THREAD

**Issue by no1ross** [DataAction/AdoNetCore.AseClient#23]
Are there plans to add support to use this package in a .net Standard Class Library, and then use a .net Core Application as the Host?

**Comment by senseibaka** [comment]
Hi @no1ross currently no plan, but my guess is that this wouldn't be much of a hassle to add.
It may just be that we need to add `netstandard2.0` to `<TargetFrameworks />` in the `csproj`.

**Comment by senseibaka** [comment]
This will be in the next release
