### ISSUE TITLE
Trying to set textsize

### ISSUE THREAD

**Issue by no1ross** [DataAction/AdoNetCore.AseClient#24]
Hi,

I am trying to set the text size if both the connection string and in code, as seen below:

`Data Source='***';Port='***';UID='***';Pwd='***';Database='***';Charset='iso_1';Pooling=True;Min Pool Size=10;Application Name='***';TextSize=2147483647;ConnectionIdleTimeout=240`

`            
            using (var connection = new AseConnection(_dbConnectionStringFactory.GetConnectionString()))
            {
                await connection.OpenAsync();

                using (var command = connection.CreateCommand())
                {
                    command.CommandText = @"
                                SET TEXTSIZE 2147483647 
                                SELECT DocumentSchemaID, AlgorithmRevisionGuidIDF, RevisionPayloadTXT 
                                FROM AlgorithmSnapshot
                                WHERE AlgorithmRevisionGuidIDF='" + revisionGuid + "'";

                    using (var reader = command.ExecuteReader())
                    {
                        // Get the results.
                        while (reader.Read())
                        {
                            var snapshot = new AlgorithmSnapshot();
                            snapshot.DocumentSchemaID = Convert.ToInt32(reader.GetString(0));
                            snapshot.AlgorithmRevisionGuidIDF = reader.GetString(1);
                            snapshot.RevisionPayloadTXT = reader.GetString(2);
                            return snapshot;
                        }
                    }
                }
            }
`

But the data coming back in the payload is still getting truncated to the default 13k or so.  Am I doing something wrong, or is there an issue?

Thanks,
Andrew

**Comment by senseibaka** [comment]
Hi Andrew,

`TextSize` is supported in the connection string (and of course, if you want to, you can set it at query-time).

I wrote up a quick test to try and replicate your issue, but it worked for me.
The test is available at [this gist](https://gist.github.com/senseibaka/daf902af1cd5f42e39889204f4e5aecc) -- does it work for you?

Cheers,
Nick

**Comment by no1ross** [comment]
Hi Nick,

I was able to successfully run that test and all Integration tests from the repo, on a database that I had dbo permissions.  I'll do further investigation on my end.

BTW: Thank you so much for this contribution, this just might be a game changer for our re-platforming.  We were at a standstill due to lack of a .net Core driver for Ase.

**Comment by senseibaka** [comment]
Thanks Andrew, that means a lot. We were very much frustrated with the lack of a .net core driver... so frustrated in fact that we started writing this 😜.

If after your investigations you do still find an issue, let us know or you can also submit a PR with the fix
