### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by MaceWindu** [DataAction/AdoNetCore.AseClient#45]
Hello

I'm currently working on adding support for this provider to linq2db library (https://github.com/linq2db/linq2db/pull/1159).

We have a lot of tests for native provider already and reuse them for your provider. While all those tests pass for native provider, for this provider we have a lot of failing tests.

Should I add separate issue for each failure or we can have this as meta-issue and work together on them?
Also we can discuss stuff in Slack to make communication more productive.

**Comment by senseibaka** [comment]
Hi @MaceWindu , thanks for the interest!

For tracking purposes, it makes sense to break this down into multiple Issues, perhaps with into a milestone entry labeled `linq2db-integration`.

Looking at the linked PR, there are quite a lot of failing tests (365), which would make issue-writing a long and arduous process. So, can the failing tests be grouped into broader categories?

Happy to discuss more in detail on Slack

**Comment by MaceWindu** [comment]
I think our time difference is too big  :)
For now I will just go through tests one-by-one and report issues.

**Comment by senseibaka** [comment]
Thanks for raising them.

Yeah, time difference might be too big, it's nearly bed time here 😉

**Comment by MaceWindu** [comment]
Ok, I've reviewed all tests - many of them were just automatically enabled for new provider and should have been disabled as we don't run them for native provider too.
Looks like I created issues for all observed unique failures.

**Comment by senseibaka** [comment]
Thanks, I'll close this issue now that the others have been raised

**Comment by MaceWindu** [comment]
I've rerun all our Sybase tests with recent master and all of them pass for AdoNetCore provider! Great job!
