### ISSUE TITLE
Prevent SQL injection

### ISSUE THREAD

**Issue by sheikhjabootie** [DataAction/AdoNetCore.AseClient#5]
String values can contain special SQL characters like single quotes that can be use to perform SQL injection. Ensure these are escaped when using parameterised commands.

**Comment by senseibaka** [comment]
The parameters are serialized straight to tokens (`TDS_PARAMFMT2` and `TDS_PARAMS`) sent over the wire, rather than being embedded in the CommandText through some stringy building/concatenation mechanism.

So I don't think we need to do anything special here.

**Comment by sheikhjabootie** [comment]
It's going to take me another hour to download ASE, but I'll create some tests around this specifically.
