### ISSUE TITLE
System.OverflowException on ExecuteReader() call

### ISSUE THREAD

**Issue by ArtyomVoronov** [DataAction/AdoNetCore.AseClient#60]
Every call of ExecuteReader() and ExecuteReaderAsync() throws System.OverflowException: 'Array dimensions exceeded supported range.'.

**Comment by senseibaka** [comment]
@ArtyomVoronov can you provide more detail? e.g. What command/parameters are you running, and against what kind of data?
Thanks

**Comment by ArtyomVoronov** [comment]
@senseibaka 
This code works:
`command.CommandText = "SELECT COUNT(*) FROM SOME_TABLE";
var count = command.ExecuteScalar();
`

This doesn't work:
`command.CommandText = "SELECT Id, SOME_FIELD FROM SOME_TABLE";
using(var reader = command.ExecuteReader())
`
Id - int, SOME_FIELD - string. 

Thanks

**Comment by senseibaka** [comment]
@ArtyomVoronov Given the information provided, I haven't been able to reproduce the issue ([see this diff](https://github.com/DataAction/AdoNetCore.AseClient/commit/c5afce79149dbe0e6f18f85d2090bb4bc76cc03e#diff-53a3771c3c6f1b1ac64c1c10af817047R1024)).

Can you provide a test case that reproduces the problem please?
