### ISSUE TITLE
Dispose(bool) should not throw if called more than once

### ISSUE THREAD

**Issue by bbarry** [DataAction/AdoNetCore.AseClient#63]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

> ✓ **DO** allow the `Dispose(bool)` method to be called more than once. The method might choose to do nothing after the first call. 

> X **AVOID** throwing an exception from within `Dispose(bool)` except under critical situations where the containing process has been corrupted (leaks, inconsistent shared state, etc.). 

bugs:
https://github.com/DataAction/AdoNetCore.AseClient/blob/c6e9e59ae693d4bb2c9054ef084debaa3e734aa5/src/AdoNetCore.AseClient/AseTransaction.cs#L146

(also `base.Dispose(disposing)` should be called immediately at the start of the method instead of inside that `if`)

https://github.com/DataAction/AdoNetCore.AseClient/blob/c6e9e59ae693d4bb2c9054ef084debaa3e734aa5/src/AdoNetCore.AseClient/AseCommand.cs#L354

https://github.com/DataAction/AdoNetCore.AseClient/blob/c6e9e59ae693d4bb2c9054ef084debaa3e734aa5/src/AdoNetCore.AseClient/AseConnection.cs#L124

The general method for overriding dispose should look like this:

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (_isDisposed) return;
        if (disposing)
        {
            // clean up
        }
        _isDisposed = true;        
    }

(`DbConnection` for example will call an event handler for an EventDisposed component event during disposal that the implementation here doesn't)

Additionally there are minor semantic differences between this driver and the SAP driver in that this driver throws `ObjectDisposedException` in methods of `AseConnection` after you have disposed where the SAP driver does not (though the SAP driver often doesn't do what you intend in these circumstances and probably should). For example you can add and remove handlers to InfoMessage after disposing with the SAP driver. 

The guidelines for the dispose pattern also state:

> ✓ **CONSIDER** providing method `Close()`, in addition to the `Dispose()`, if close is standard terminology in the area. 
> 
> When doing so, it is important that you make the `Close` implementation identical to `Dispose` and consider implementing the `IDisposable.Dispose` method explicitly. 

But that would require a larger semantic difference between this driver and the SAP one... honestly I think the SAP driver is riddled with bugs surrounding `Close` and `Dispose` and would prefer stricter adherence to the design guidelines.

**Comment by senseibaka** [comment]
Thanks, this appears to be intentional (consistency with checking `_isDisposed` on other members), and is technically allowed; however, it is a bit silly and is easily fixable.

In regards to replication of the SAP driver's behaviour, I think that we absolutely should replicate its "happy path" stuff, but think hard about everything else. We don't particularly want to replicate the bugs.
