### ISSUE TITLE
Expose AseCommand empty parameter constructor

### ISSUE THREAD

**Issue by beppler** [DataAction/AdoNetCore.AseClient#67]
The AseParameter classe is exposing only the overload that receives an AseConnection parameter that is needed if you want to use the provider with NHibernate.

Trying to use this overload, but passing null throws a NullRefenceException on [this line](https://github.com/DataAction/AdoNetCore.AseClient/blob/master/src/AdoNetCore.AseClient/AseCommand.cs#L41).

Can you expose the empty parameter constructor (it is internal now) and make the NamedParamters on [this line](https://github.com/DataAction/AdoNetCore.AseClient/blob/master/src/AdoNetCore.AseClient/AseCommand.cs#L34) property true in this case?

**Comment by senseibaka** [comment]
Thanks for raising this.

**Parameter-less constructor**
Agreed, the reference driver exposes this, so in the interests of drop-in replacement we should too.

In addition, the reference driver exposes these constructors:
* `public AseCommand(string cmdText)`
* `public AseCommand(string cmdText, AseConnection connection)`
* `public AseCommand(string cmdText, AseConnection connection, AseTransaction transaction)`

So I will go ahead and add these as well.

**NamedParameters**
Yes, I agree this should default to `true`; it's a sensible setting to have turned on.
Also, we don't yet support `NamedParameters = false`, so defaulting to `false` is a bit silly, isn't it?

**Comment by beppler** [comment]
Wow, that is fast, thanks!
