### ISSUE TITLE
Implement prepared statements

### ISSUE THREAD

**Issue by sheikhjabootie** [DataAction/AdoNetCore.AseClient#8]
The IDbCommand and DbCommand types define a method Prepare that implementers are required to implement.

The intention is that this command instructs the server to compile the query so that repeated executions are faster.

Our current implementation is a no-op. We should consider implementing this.

**Comment by senseibaka** [comment]
`TDS_DYNAMIC` and `TDS_DYNAMIC2' tokens appear to be what we'd use to prepare/execute prepared statements.

According to the TDS spec, prepared statements have a lifetime of the current client session

**Comment by senseibaka** [comment]
I implemented Prepare(), but then discovered that the server responds with 
> Dynamic SQL error - Prepared statement '1' does not exist.

So, I looked to what the .net 4 driver is doing and discovered that under the hood, it's not actually preparing the statement at all --rather it just sends a language token (regular token for executing sql) every time we tell the command to execute.
