### ISSUE TITLE
Add ASEClientFactory to other versions of framework besides .net core 2.1

### ISSUE THREAD

**Issue by rgarrison12345** [DataAction/AdoNetCore.AseClient#86]
Is there a specific reason why the client factory class cannot be added to the other supported .net versions?    

Specifically .NET Standard 2.0, .NET Core 2.0, .NET 4.6.  I understand why it wouldn't be added to .net core 1.0/1.1 the full ADO.NET System.Data/System.Data.Common API wasn't completely realized until .NET standard 2.0.

If not I can help with this effort.

**Comment by senseibaka** [comment]
Hi @rgarrison12345 ,

As far as I can tell, there's no specific reason.
If I had to make a guess, I'd probably chalk it up to a misjudgement as to what's supported in the various versions/standards...

Thanks for pointing this out, I will add a fix for next release :)
