### ISSUE TITLE
AdoNetCore.AseClient.AseException: 'Server environment changed to unsupported charset '

### ISSUE THREAD

**Issue by anawar82** [DataAction/AdoNetCore.AseClient#89]
I get AdoNetCore.AseClient.AseException: 'Server environment changed to unsupported charset ' when trying to open the connection
![image](https://user-images.githubusercontent.com/44231849/47419265-80b80a80-d784-11e8-82b4-1e00d4bd37a8.png)

**Comment by senseibaka** [comment]
Hi @anawar82,

Our driver throws this exception when the server tells it to use a charset it doesn't support. Usually this charset's name would appear at the end of the exception message (`throw new AseException($"Server environment changed to unsupported charset {change.NewValue}");`), so that's weird.

Can you tell me what the charset of your database/server is?

Cheers

**Comment by anawar82** [comment]
Code Page 850 (Multilingual)

**Comment by senseibaka** [comment]
Thanks @anawar82 

So .net core does not natively support `ibm850` (refer [these msdn remarks](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-1.0#remarks)). Therefore, the driver in its current state *also* doesn't support `ibm850`.

There are a couple of options as to how support could be added to the driver:

1. Implement an `EncodingProvider` within the driver's code.
2. Leverage the `System.Text.Encoding.CodePages` nuget package - see https://stackoverflow.com/a/37870346/242311

I'm not entirely happy with either option, in particular:

* Implementing an `EncodingProvider` seems like a waste when probably someone has already implemented it, and it feels like implementing any text encoding is outside the domain of this driver's purpose. In short, it feels a bit "bloaty" to add it.
* I'm reluctant to add another dependency to the driver. Ideally I would like it to remain relatively lean.

**However,** the above does not help you use the driver, so here's a third option which might help us both:
* Add to the driver implicit support for [as many of the charsets](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38421.1600/doc/html/san1335472569391.html) as possible, and leave it to the consumer to register their own `EncodingProvider` (either by implementing one, or adding an appropriate project reference).
* Add some documentation to this GitHub project explaining how to add non-standard charset support.

Would you be happy with that solution?
