### ISSUE TITLE
AseConnection is missing public static method ClearPools

### ISSUE THREAD

**Issue by bbarry** [DataAction/AdoNetCore.AseClient#92]
`Sybase.Data.AseClient.AseConnection` has a method:

`public static void ClearPools()` which loops over all the pools in the connection pool manager and calls clear on them.

I'm not sure it should be implemented but the lack of this method does cause errors for people using it.

**Comment by senseibaka** [comment]
Thanks @bbarry 
I've submitted a PR which adds the stub
