### ISSUE TITLE
Parameter handling broke between 0.11.0 and 0.13.0

### ISSUE THREAD

**Issue by chgeuer** [DataAction/AdoNetCore.AseClient#96]
String-based ODBC parameters arrive truncated at ASE. I want to run a parametrized `USE master` command, with the `master` database name being a parameter. 

- In v0.11.0 it works.
- In v0.13.0, the problem occurs. 

## Failure

```csharp
command.Parameters.Add(parameterName: "dbname", parameterValue: "master");
command.CommandText = $"USE @dbname";
await command.ExecuteNonQueryAsync(cancellationToken);
```

- My C# string is recognized as `TDS_LONGBINARY` parameter, i.e. "master" becomes butchered to be "m". 
- In `AdoNetCore.AseClient.Internal.ValueWriter.WriteTDS_LONGBINARY`, I see that my "master" becomes serialized as 12 bytes `[109, 0, 97, 0, 115, 0, 116, 0, 101, 0, 114, 0]`. 

### Exception Details

```text
Unhandled Exception: AdoNetCore.AseClient.AseException: 
Attempt to locate entry in sysdatabases for database 'm' by name failed - 
no entry found under that name. Make sure that name is entered properly.

   at AdoNetCore.AseClient.Internal.Handler.MessageTokenHandler.AssertNoErrors()
   at AdoNetCore.AseClient.Internal.InternalConnection.InternalExecuteAsync(...)
---
```

## Success

```csharp
command.Parameters.Add(
   new AseParameter(parameterName: "dbname", dbType: AseDbType.Text) { 
         Value = dbname 
    });
command.CommandText = $"USE @dbname";
await command.ExecuteNonQueryAsync(cancellationToken);
```

- My C# string is recognized as `TDS_VARCHAR` parameter, and "master" remains "master. 
- `AdoNetCore.AseClient.Internal.ValueWriter.WriteTDS_VARCHAR` writes `[109, 97, 115, 116, 101, 114]` to the pipe.

### Full sample code

```csharp
var cts = new CancellationTokenSource();
var cancellationToken = cts.Token;
using (var connection = new AseConnection(connectionString: DemoUtils.DemoConnectionStringSapsa))
{
    await connection.OpenAsync(cancellationToken: cancellationToken);

    using (var command = connection.CreateCommand())
    {
        string dbname = "master";

        // command.Parameters.Add(new AseParameter(parameterName: "dbname", dbType: AseDbType.Text) { Value = dbname });
        command.Parameters.Add(parameterName: "dbname", parameterValue: dbname);

        command.CommandText = $"USE @dbname";
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
```

**Comment by senseibaka** [comment]
Thanks @chgeuer, I believe this is the result of PR #80 .

It looks like the reference driver's doing some type inference if the parameter's type is not specified, and we should replicate this.
