### ISSUE TITLE
Stream was too long

### ISSUE THREAD

**Issue by thierri** [DataAction/AdoNetCore.AseClient#99]
Hi Guys,

We are trying to select a huge dataset (about 14 million lines, with 28 columns). Than, suddenly we receive the error:

--- Stream is too long on the method ReceiveTokens, inside RegularSocket.

We are monitoring the memory usage on the server, and it was ok (about 50% usage).

Any ideas?

Thnks

**Comment by senseibaka** [comment]
Hi @thierri ,

Under the hood we make use of `MemoryStream` to buffer response bytes prior to parsing them and returning the data to you.

I did a little reading and found that `MemoryStream` has a hard limit of 2GB.

Something I'd be interested in doing is changing the driver to not buffer the entire response before returning it to the user, but I can't say when this change would be available.

Cheers

**Comment by c-j-hughes** [comment]
Fixed as of 0.14.0
